FROM repo.despera.space/iru/rocm:5.2.3
ENV CC=/opt/rocm/llvm/bin/clang
ENV CXX=/opt/rocm/llvm/bin/clang++
RUN apt-get update && apt-get install -y git make
RUN git clone https://github.com/SlyEcho/llama.cpp.git /app
RUN apt-get clean
WORKDIR /app
RUN make LLAMA_HIPBLAS=1 -j
